openapi: 3.0.1
info:
  description: A REST interface for state queries, transaction generation and broadcasting.
  title: Gaia-Lite for Cosmos
  version: "3.0"
servers:
- url: https://stargate.cosmos.network/
tags:
- description: Search, encode, or broadcast transactions.
  name: Transactions
- description: Tendermint APIs, such as query blocks, transactions and validatorset
  name: Tendermint RPC
- description: Authenticate accounts
  name: Auth
- description: Create and broadcast transactions
  name: Bank
- description: Query app version
  name: Misc
paths:
  /node_info:
    get:
      description: Information about the connected node
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200'
          description: Node status
        "500":
          content: {}
          description: Failed to query node status
      summary: The properties of the connected node
      tags:
      - Tendermint RPC
  /syncing:
    get:
      description: Get if the node is currently syning with other nodes
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_1'
          description: Node syncing status
        "500":
          content: {}
          description: Server internal error
      summary: Syncing state of node
      tags:
      - Tendermint RPC
  /blocks/latest:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockQuery'
          description: The latest block
        "500":
          content: {}
          description: Server internal error
      summary: Get the latest block
      tags:
      - Tendermint RPC
  /blocks/{height}:
    get:
      parameters:
      - description: Block height
        example: 1
        in: path
        name: height
        required: true
        schema:
          type: number
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlockQuery'
          description: The block at a specific height
        "400":
          content: {}
          description: Invalid height
        "404":
          content: {}
          description: Request block height doesn't
        "500":
          content: {}
          description: Server internal error
      summary: Get a block at a certain height
      tags:
      - Tendermint RPC
  /validatorsets/latest:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: The validator set at the latest block height
        "500":
          content: {}
          description: Server internal error
      summary: Get the latest validator set
      tags:
      - Tendermint RPC
  /validatorsets/{height}:
    get:
      parameters:
      - description: Block height
        example: 1
        in: path
        name: height
        required: true
        schema:
          type: number
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_2'
          description: The validator set at a specific block height
        "400":
          content: {}
          description: Invalid height
        "404":
          content: {}
          description: Block at height not available
        "500":
          content: {}
          description: Server internal error
      summary: Get a validator set a certain height
      tags:
      - Tendermint RPC
  /txs/{hash}:
    get:
      description: Retrieve a transaction using its hash.
      parameters:
      - description: Tx hash
        example: BCBE20E8D46758B96AE5883B792858296AC06E51435490FBDCAE25A72B3CC76B
        in: path
        name: hash
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/TxQuery'
          description: Tx with the provided hash
        "500":
          content: {}
          description: Internal Server Error
      summary: Get a Tx by hash
      tags:
      - Transactions
  /txs:
    get:
      description: Search transactions by events.
      parameters:
      - description: 'transaction events such as ''message.action=send'' which results
          in the following endpoint: ''GET /txs?message.action=send''. note that each
          module documents its own events. look for xx_events.md in the corresponding
          cosmos-sdk/docs/spec directory'
        example: send
        in: query
        name: message.action
        schema:
          type: string
      - description: 'transaction tags with sender: ''GET /txs?message.action=send&message.sender=cosmos16xyempempp92x9hyzz9wrgf94r6j9h5f06pxxv'''
        example: cosmos16xyempempp92x9hyzz9wrgf94r6j9h5f06pxxv
        in: query
        name: message.sender
        schema:
          type: string
      - description: Page number
        example: 1
        in: query
        name: page
        schema:
          type: integer
      - description: Maximum number of items per page
        example: 1
        in: query
        name: limit
        schema:
          type: integer
      - description: transactions on blocks with height greater or equal this value
        example: 25
        in: query
        name: tx.minheight
        schema:
          type: integer
      - description: transactions on blocks with height less than or equal this value
        example: 800000
        in: query
        name: tx.maxheight
        schema:
          type: integer
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedQueryTxs'
          description: All txs matching the provided events
        "400":
          content: {}
          description: Invalid search events
        "500":
          content: {}
          description: Internal Server Error
      summary: Search transactions
      tags:
      - Transactions
    post:
      description: Broadcast a signed tx to a full node
      requestBody:
        $ref: '#/components/requestBodies/inline_object'
        content:
          application/json:
            schema:
              properties:
                tx:
                  $ref: '#/components/schemas/StdTx'
                mode:
                  example: block
                  type: string
              type: object
        description: The tx must be a signed StdTx. The supported broadcast modes
          include `"block"`(return after tx commit), `"sync"`(return afer CheckTx)
          and `"async"`(return right away).
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_3'
          description: Tx broadcasting result
        "500":
          content: {}
          description: Internal Server Error
      summary: Broadcast a signed tx
      tags:
      - Transactions
      x-codegen-request-body-name: txBroadcast
  /txs/encode:
    post:
      description: Encode a transaction (signed or not) from JSON to base64-encoded
        Amino serialized bytes
      requestBody:
        $ref: '#/components/requestBodies/inline_object_1'
        content:
          application/json:
            schema:
              properties:
                tx:
                  $ref: '#/components/schemas/StdTx'
              type: object
        description: The tx to encode
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_4'
          description: The tx was successfully decoded and re-encoded
        "400":
          content: {}
          description: The tx was malformated
        "500":
          content: {}
          description: Server internal error
      summary: Encode a transaction to the Amino wire format
      tags:
      - Transactions
      x-codegen-request-body-name: tx
  /txs/decode:
    post:
      description: Decode a transaction (signed or not) from base64-encoded Amino
        serialized bytes to JSON
      requestBody:
        $ref: '#/components/requestBodies/inline_object_2'
        content:
          application/json:
            schema:
              properties:
                tx:
                  example: SvBiXe4KPqijYZoKFFHEzJ8c2HPAfv2EFUcIhx0yPagwEhTy0vPA+GGhCEslKXa4Af0uB+mfShoMCgVzdGFrZRIDMTAwEgQQwJoM
                  type: string
              type: object
        description: The tx to decode
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/StdTx'
          description: The tx was successfully decoded
        "400":
          content: {}
          description: The tx was malformated
        "500":
          content: {}
          description: Server internal error
      summary: Decode a transaction from the Amino wire format
      tags:
      - Transactions
      x-codegen-request-body-name: tx
  /bank/balances/{address}:
    get:
      parameters:
      - description: Account address in bech32 format
        example: cosmos16xyempempp92x9hyzz9wrgf94r6j9h5f06pxxv
        in: path
        name: address
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_5'
          description: Account balances
        "500":
          content: {}
          description: Server internal error
      summary: Get the account balances
      tags:
      - Bank
  /auth/accounts/{address}:
    get:
      parameters:
      - description: Account address
        example: cosmos16xyempempp92x9hyzz9wrgf94r6j9h5f06pxxv
        in: path
        name: address
        required: true
        schema:
          type: string
      responses:
        "200":
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/inline_response_200_6'
          description: Account information on the blockchain
        "500":
          content: {}
          description: Server internel error
      summary: Get the account information on blockchain
      tags:
      - Auth
components:
  requestBodies:
    inline_object_1:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_1'
      required: true
    inline_object:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object'
      required: true
    inline_object_2:
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/inline_object_2'
      required: true
  schemas:
    CheckTxResult:
      example:
        code: 0
        data: data
        log: log
        gas_used: 5000
        gas_wanted: 10000
        info: info
        tags:
        - ""
        - ""
      properties:
        code:
          type: integer
        data:
          type: string
        gas_used:
          type: integer
        gas_wanted:
          type: integer
        info:
          type: string
        log:
          type: string
        tags:
          items:
            $ref: '#/components/schemas/KVPair'
          type: array
      type: object
    DeliverTxResult:
      example:
        code: 5
        data: data
        log: log
        gas_used: 5000
        gas_wanted: 10000
        info: info
        tags:
        - ""
        - ""
      properties:
        code:
          type: integer
        data:
          type: string
        gas_used:
          type: integer
        gas_wanted:
          type: integer
        info:
          type: string
        log:
          type: string
        tags:
          items:
            $ref: '#/components/schemas/KVPair'
          type: array
      type: object
    BroadcastTxCommitResult:
      properties:
        check_tx:
          $ref: '#/components/schemas/CheckTxResult'
        deliver_tx:
          $ref: '#/components/schemas/DeliverTxResult'
        hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        height:
          type: integer
      type: object
    KVPair:
      example:
        value: value
        key: key
      properties:
        key:
          type: string
        value:
          type: string
      type: object
    Msg:
      example:
        type: type
        value:
          amount:
          - amount: "50"
            denom: stake
          - amount: "50"
            denom: stake
          to_address: to_address
          from_address: from_address
      properties:
        type:
          type: string
        value:
          $ref: '#/components/schemas/Msg_value'
      type: object
    Address:
      description: bech32 encoded address
      example: cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27
      type: string
    ValidatorAddress:
      description: bech32 encoded address
      example: cosmosvaloper16xyempempp92x9hyzz9wrgf94r6j9h5f2w4n2l
      type: string
    Coin:
      example:
        amount: "50"
        denom: stake
      properties:
        denom:
          example: stake
          type: string
        amount:
          example: "50"
          type: string
      type: object
    Hash:
      example: EE5F3404034C524501629B56E0DDC38FAD651F04
      type: string
    TxQuery:
      example:
        result:
          log: log
          gas_used: "26354"
          gas_wanted: "200000"
          tags:
          - value: value
            key: key
          - value: value
            key: key
        code: 0
        tx:
          value:
            msg:
            - type: type
              value:
                amount:
                - amount: "50"
                  denom: stake
                - amount: "50"
                  denom: stake
                to_address: to_address
                from_address: from_address
            - type: type
              value:
                amount:
                - amount: "50"
                  denom: stake
                - amount: "50"
                  denom: stake
                to_address: to_address
                from_address: from_address
            fee:
              amount:
              - amount: "50"
                denom: stake
              - amount: "50"
                denom: stake
              gas: gas
            memo: memo
            signatures:
            - account_number: "0"
              sequence: "0"
              signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
              pub_key:
                type: tendermint/PubKeySecp256k1
                value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
            - account_number: "0"
              sequence: "0"
              signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
              pub_key:
                type: tendermint/PubKeySecp256k1
                value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
        txhash: D085138D913993919295FF4B0A9107F1F2CDE0D37A87CE0644E217CBF3B49656
        height: "368"
      properties:
        code:
          type: integer
        txhash:
          example: D085138D913993919295FF4B0A9107F1F2CDE0D37A87CE0644E217CBF3B49656
          type: string
        height:
          example: "368"
          type: string
        tx:
          $ref: '#/components/schemas/StdTx'
        result:
          $ref: '#/components/schemas/TxQuery_result'
      type: object
    PaginatedQueryTxs:
      example:
        page_number: 1.0
        page_total: 1.0
        total_count: 1.0
        count: 1.0
        limit: 30.0
        txs:
        - result:
            log: log
            gas_used: "26354"
            gas_wanted: "200000"
            tags:
            - value: value
              key: key
            - value: value
              key: key
          code: 0
          tx:
            value:
              msg:
              - type: type
                value:
                  amount:
                  - amount: "50"
                    denom: stake
                  - amount: "50"
                    denom: stake
                  to_address: to_address
                  from_address: from_address
              - type: type
                value:
                  amount:
                  - amount: "50"
                    denom: stake
                  - amount: "50"
                    denom: stake
                  to_address: to_address
                  from_address: from_address
              fee:
                amount:
                - amount: "50"
                  denom: stake
                - amount: "50"
                  denom: stake
                gas: gas
              memo: memo
              signatures:
              - account_number: "0"
                sequence: "0"
                signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
                pub_key:
                  type: tendermint/PubKeySecp256k1
                  value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
              - account_number: "0"
                sequence: "0"
                signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
                pub_key:
                  type: tendermint/PubKeySecp256k1
                  value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
          txhash: D085138D913993919295FF4B0A9107F1F2CDE0D37A87CE0644E217CBF3B49656
          height: "368"
        - result:
            log: log
            gas_used: "26354"
            gas_wanted: "200000"
            tags:
            - value: value
              key: key
            - value: value
              key: key
          code: 0
          tx:
            value:
              msg:
              - type: type
                value:
                  amount:
                  - amount: "50"
                    denom: stake
                  - amount: "50"
                    denom: stake
                  to_address: to_address
                  from_address: from_address
              - type: type
                value:
                  amount:
                  - amount: "50"
                    denom: stake
                  - amount: "50"
                    denom: stake
                  to_address: to_address
                  from_address: from_address
              fee:
                amount:
                - amount: "50"
                  denom: stake
                - amount: "50"
                  denom: stake
                gas: gas
              memo: memo
              signatures:
              - account_number: "0"
                sequence: "0"
                signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
                pub_key:
                  type: tendermint/PubKeySecp256k1
                  value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
              - account_number: "0"
                sequence: "0"
                signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
                pub_key:
                  type: tendermint/PubKeySecp256k1
                  value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
          txhash: D085138D913993919295FF4B0A9107F1F2CDE0D37A87CE0644E217CBF3B49656
          height: "368"
      properties:
        total_count:
          example: 1.0
          type: number
        count:
          example: 1.0
          type: number
        page_number:
          example: 1.0
          type: number
        page_total:
          example: 1.0
          type: number
        limit:
          example: 30.0
          type: number
        txs:
          items:
            $ref: '#/components/schemas/TxQuery'
          type: array
      type: object
    StdTx:
      example:
        value:
          msg:
          - type: type
            value:
              amount:
              - amount: "50"
                denom: stake
              - amount: "50"
                denom: stake
              to_address: to_address
              from_address: from_address
          - type: type
            value:
              amount:
              - amount: "50"
                denom: stake
              - amount: "50"
                denom: stake
              to_address: to_address
              from_address: from_address
          fee:
            amount:
            - amount: "50"
              denom: stake
            - amount: "50"
              denom: stake
            gas: gas
          memo: memo
          signatures:
          - account_number: "0"
            sequence: "0"
            signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
            pub_key:
              type: tendermint/PubKeySecp256k1
              value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
          - account_number: "0"
            sequence: "0"
            signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
            pub_key:
              type: tendermint/PubKeySecp256k1
              value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
      properties:
        value:
          $ref: '#/components/schemas/StdTx_value'
      type: object
    BlockID:
      example:
        parts:
          total: 0.0
          hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        hash: EE5F3404034C524501629B56E0DDC38FAD651F04
      properties:
        hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        parts:
          $ref: '#/components/schemas/BlockID_parts'
      type: object
    BlockHeader:
      example:
        validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        chain_id: cosmoshub-2
        consensus_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        total_txs: 35.0
        proposer_address: cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27
        next_validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        version:
          app: "0"
          block: "10"
        data_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        last_results_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        last_block_id:
          parts:
            total: 0.0
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        evidence_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        num_txs: 0.0
        app_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        time: 2017-12-30T05:53:09.287+01:00
        height: 1.0
        last_commit_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
      properties:
        chain_id:
          example: cosmoshub-2
          type: string
        height:
          example: 1.0
          type: number
        time:
          example: 2017-12-30T05:53:09.287+01:00
          type: string
        num_txs:
          example: 0.0
          type: number
        last_block_id:
          $ref: '#/components/schemas/BlockID'
        total_txs:
          example: 35.0
          type: number
        last_commit_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        data_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        validators_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        next_validators_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        consensus_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        app_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        last_results_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        evidence_hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
        proposer_address:
          description: bech32 encoded address
          example: cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27
          type: string
        version:
          $ref: '#/components/schemas/BlockHeader_version'
      type: object
    Block:
      example:
        evidence:
        - evidence
        - evidence
        last_commit:
          block_id:
            parts:
              total: 0.0
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          precommits:
          - round: "0"
            signature: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
            validator_address: validator_address
            validator_index: "0"
            type: 2.0
            block_id:
              parts:
                total: 0.0
                hash: EE5F3404034C524501629B56E0DDC38FAD651F04
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            height: "0"
            timestamp: 2017-12-30T05:53:09.287+01:00
          - round: "0"
            signature: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
            validator_address: validator_address
            validator_index: "0"
            type: 2.0
            block_id:
              parts:
                total: 0.0
                hash: EE5F3404034C524501629B56E0DDC38FAD651F04
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            height: "0"
            timestamp: 2017-12-30T05:53:09.287+01:00
        header:
          validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          chain_id: cosmoshub-2
          consensus_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          total_txs: 35.0
          proposer_address: cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27
          next_validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          version:
            app: "0"
            block: "10"
          data_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          last_results_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          last_block_id:
            parts:
              total: 0.0
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          evidence_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          num_txs: 0.0
          app_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          time: 2017-12-30T05:53:09.287+01:00
          height: 1.0
          last_commit_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        txs:
        - txs
        - txs
      properties:
        header:
          $ref: '#/components/schemas/BlockHeader'
        txs:
          items:
            type: string
          type: array
        evidence:
          items:
            type: string
          type: array
        last_commit:
          $ref: '#/components/schemas/Block_last_commit'
      type: object
    BlockQuery:
      example:
        block:
          evidence:
          - evidence
          - evidence
          last_commit:
            block_id:
              parts:
                total: 0.0
                hash: EE5F3404034C524501629B56E0DDC38FAD651F04
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            precommits:
            - round: "0"
              signature: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
              validator_address: validator_address
              validator_index: "0"
              type: 2.0
              block_id:
                parts:
                  total: 0.0
                  hash: EE5F3404034C524501629B56E0DDC38FAD651F04
                hash: EE5F3404034C524501629B56E0DDC38FAD651F04
              height: "0"
              timestamp: 2017-12-30T05:53:09.287+01:00
            - round: "0"
              signature: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
              validator_address: validator_address
              validator_index: "0"
              type: 2.0
              block_id:
                parts:
                  total: 0.0
                  hash: EE5F3404034C524501629B56E0DDC38FAD651F04
                hash: EE5F3404034C524501629B56E0DDC38FAD651F04
              height: "0"
              timestamp: 2017-12-30T05:53:09.287+01:00
          header:
            validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            chain_id: cosmoshub-2
            consensus_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            total_txs: 35.0
            proposer_address: cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27
            next_validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            version:
              app: "0"
              block: "10"
            data_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            last_results_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            last_block_id:
              parts:
                total: 0.0
                hash: EE5F3404034C524501629B56E0DDC38FAD651F04
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            evidence_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            num_txs: 0.0
            app_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            time: 2017-12-30T05:53:09.287+01:00
            height: 1.0
            last_commit_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          txs:
          - txs
          - txs
        block_meta:
          header:
            validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            chain_id: cosmoshub-2
            consensus_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            total_txs: 35.0
            proposer_address: cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27
            next_validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            version:
              app: "0"
              block: "10"
            data_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            last_results_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            last_block_id:
              parts:
                total: 0.0
                hash: EE5F3404034C524501629B56E0DDC38FAD651F04
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            evidence_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            num_txs: 0.0
            app_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            time: 2017-12-30T05:53:09.287+01:00
            height: 1.0
            last_commit_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          block_id:
            parts:
              total: 0.0
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
      properties:
        block_meta:
          $ref: '#/components/schemas/BlockQuery_block_meta'
        block:
          $ref: '#/components/schemas/Block'
      type: object
    BaseReq:
      properties:
        from:
          description: Sender address or Keybase name to generate a transaction
          example: cosmos1g9ahr6xhht5rmqven628nklxluzyv8z9jqjcmc
          type: string
        memo:
          example: Sent via Cosmos Voyager ðŸš€
          type: string
        chain_id:
          example: Cosmos-Hub
          type: string
        account_number:
          example: "0"
          type: string
        sequence:
          example: "1"
          type: string
        gas:
          example: "200000"
          type: string
        gas_adjustment:
          example: "1.2"
          type: string
        fees:
          items:
            $ref: '#/components/schemas/Coin'
          type: array
        simulate:
          description: Estimate gas for a transaction (cannot be used in conjunction
            with generate_only)
          example: false
          type: boolean
      type: object
    TendermintValidator:
      example:
        address: cosmosvaloper16xyempempp92x9hyzz9wrgf94r6j9h5f2w4n2l
        proposer_priority: "1000"
        pub_key: cosmosvalconspub1zcjduepq0vu2zgkgk49efa0nqwzndanq5m4c7pa3u4apz4g2r9gspqg6g9cs3k9cuf
        voting_power: "1000"
      properties:
        address:
          description: bech32 encoded address
          example: cosmosvaloper16xyempempp92x9hyzz9wrgf94r6j9h5f2w4n2l
          type: string
        pub_key:
          example: cosmosvalconspub1zcjduepq0vu2zgkgk49efa0nqwzndanq5m4c7pa3u4apz4g2r9gspqg6g9cs3k9cuf
          type: string
        voting_power:
          example: "1000"
          type: string
        proposer_priority:
          example: "1000"
          type: string
      type: object
    Delegation:
      properties:
        delegator_address:
          type: string
        validator_address:
          type: string
        shares:
          type: string
        balance:
          $ref: '#/components/schemas/Coin'
      type: object
    inline_response_200_application_version:
      example:
        server_name: server_name
        commit: commit
        go: go
        name: name
        client_name: client_name
        version: version
        build_tags: build_tags
      properties:
        build_tags:
          type: string
        client_name:
          type: string
        commit:
          type: string
        go:
          type: string
        name:
          type: string
        server_name:
          type: string
        version:
          type: string
    inline_response_200_node_info_protocol_version:
      example:
        app: "0"
        block: "10"
        p2p: "7"
      properties:
        p2p:
          example: "7"
          type: string
        block:
          example: "10"
          type: string
        app:
          example: "0"
          type: string
    inline_response_200_node_info_other:
      description: more information on versions
      example:
        tx_index: "true"
        rpc_address: tcp://0.0.0.0:26657
      properties:
        tx_index:
          example: "true"
          type: string
        rpc_address:
          example: tcp://0.0.0.0:26657
          type: string
    inline_response_200_node_info:
      example:
        protocol_version:
          app: "0"
          block: "10"
          p2p: "7"
        other:
          tx_index: "true"
          rpc_address: tcp://0.0.0.0:26657
        channels: channels
        listen_addr: 192.168.56.1:26656
        id: id
        moniker: validator-name
        version: 0.15.0
        network: gaia-2
      properties:
        id:
          type: string
        moniker:
          example: validator-name
          type: string
        protocol_version:
          $ref: '#/components/schemas/inline_response_200_node_info_protocol_version'
        network:
          example: gaia-2
          type: string
        channels:
          type: string
        listen_addr:
          example: 192.168.56.1:26656
          type: string
        version:
          description: Tendermint version
          example: 0.15.0
          type: string
        other:
          $ref: '#/components/schemas/inline_response_200_node_info_other'
    inline_response_200:
      example:
        node_info:
          protocol_version:
            app: "0"
            block: "10"
            p2p: "7"
          other:
            tx_index: "true"
            rpc_address: tcp://0.0.0.0:26657
          channels: channels
          listen_addr: 192.168.56.1:26656
          id: id
          moniker: validator-name
          version: 0.15.0
          network: gaia-2
        application_version:
          server_name: server_name
          commit: commit
          go: go
          name: name
          client_name: client_name
          version: version
          build_tags: build_tags
      properties:
        application_version:
          $ref: '#/components/schemas/inline_response_200_application_version'
        node_info:
          $ref: '#/components/schemas/inline_response_200_node_info'
    inline_response_200_1:
      example:
        syncing: true
      properties:
        syncing:
          type: boolean
    inline_response_200_2:
      example:
        validators:
        - address: cosmosvaloper16xyempempp92x9hyzz9wrgf94r6j9h5f2w4n2l
          proposer_priority: "1000"
          pub_key: cosmosvalconspub1zcjduepq0vu2zgkgk49efa0nqwzndanq5m4c7pa3u4apz4g2r9gspqg6g9cs3k9cuf
          voting_power: "1000"
        - address: cosmosvaloper16xyempempp92x9hyzz9wrgf94r6j9h5f2w4n2l
          proposer_priority: "1000"
          pub_key: cosmosvalconspub1zcjduepq0vu2zgkgk49efa0nqwzndanq5m4c7pa3u4apz4g2r9gspqg6g9cs3k9cuf
          voting_power: "1000"
        block_height: block_height
      properties:
        block_height:
          type: string
        validators:
          items:
            $ref: '#/components/schemas/TendermintValidator'
          type: array
    inline_object:
      properties:
        tx:
          $ref: '#/components/schemas/StdTx'
        mode:
          example: block
          type: string
      type: object
    inline_response_200_3:
      example:
        codespace: codespace
        code: 0.8008281904610115
        gas_used: gas_used
        gas_wanted: gas_wanted
        raw_log: raw_log
        height: height
        txhash: txhash
      properties:
        height:
          type: string
        txhash:
          type: string
        codespace:
          type: string
        code:
          type: number
        raw_log:
          type: string
        gas_wanted:
          type: string
        gas_used:
          type: string
    inline_object_1:
      properties:
        tx:
          $ref: '#/components/schemas/StdTx'
      type: object
    inline_response_200_4:
      example:
        tx: The base64-encoded Amino-serialized bytes for the tx
      properties:
        tx:
          example: The base64-encoded Amino-serialized bytes for the tx
          type: string
    inline_object_2:
      properties:
        tx:
          example: SvBiXe4KPqijYZoKFFHEzJ8c2HPAfv2EFUcIhx0yPagwEhTy0vPA+GGhCEslKXa4Af0uB+mfShoMCgVzdGFrZRIDMTAwEgQQwJoM
          type: string
      type: object
    inline_response_200_5:
      example:
        result:
        - amount: "50"
          denom: stake
        - amount: "50"
          denom: stake
        height: height
      properties:
        height:
          type: string
        result:
          items:
            $ref: '#/components/schemas/Coin'
          type: array
    inline_response_200_6_result_value:
      example:
        public_key:
          type: type
          value: value
        account_number: account_number
        sequence: sequence
        address: address
        coins:
        - amount: "50"
          denom: stake
        - amount: "50"
          denom: stake
      properties:
        account_number:
          type: string
        address:
          type: string
        coins:
          items:
            $ref: '#/components/schemas/Coin'
          type: array
        public_key:
          $ref: '#/components/schemas/PublicKey'
        sequence:
          type: string
    inline_response_200_6_result:
      example:
        type: type
        value:
          public_key:
            type: type
            value: value
          account_number: account_number
          sequence: sequence
          address: address
          coins:
          - amount: "50"
            denom: stake
          - amount: "50"
            denom: stake
      properties:
        type:
          type: string
        value:
          $ref: '#/components/schemas/inline_response_200_6_result_value'
    inline_response_200_6:
      example:
        result:
          type: type
          value:
            public_key:
              type: type
              value: value
            account_number: account_number
            sequence: sequence
            address: address
            coins:
            - amount: "50"
              denom: stake
            - amount: "50"
              denom: stake
        height: height
      properties:
        height:
          type: string
        result:
          $ref: '#/components/schemas/inline_response_200_6_result'
    Msg_value:
      example:
        amount:
        - amount: "50"
          denom: stake
        - amount: "50"
          denom: stake
        to_address: to_address
        from_address: from_address
      properties:
        from_address:
          type: string
        to_address:
          type: string
        amount:
          items:
            $ref: '#/components/schemas/Coin'
          type: array
    TxQuery_result:
      example:
        log: log
        gas_used: "26354"
        gas_wanted: "200000"
        tags:
        - value: value
          key: key
        - value: value
          key: key
      properties:
        log:
          type: string
        gas_wanted:
          example: "200000"
          type: string
        gas_used:
          example: "26354"
          type: string
        tags:
          items:
            $ref: '#/components/schemas/KVPair'
          type: array
    StdTx_value_fee:
      example:
        amount:
        - amount: "50"
          denom: stake
        - amount: "50"
          denom: stake
        gas: gas
      properties:
        gas:
          type: string
        amount:
          items:
            $ref: '#/components/schemas/Coin'
          type: array
    StdTx_value_pub_key:
      example:
        type: tendermint/PubKeySecp256k1
        value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
      properties:
        type:
          example: tendermint/PubKeySecp256k1
          type: string
        value:
          example: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
          type: string
    StdTx_value_signatures:
      example:
        account_number: "0"
        sequence: "0"
        signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
        pub_key:
          type: tendermint/PubKeySecp256k1
          value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
      properties:
        signature:
          example: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
          type: string
        pub_key:
          $ref: '#/components/schemas/StdTx_value_pub_key'
        account_number:
          example: "0"
          type: string
        sequence:
          example: "0"
          type: string
    StdTx_value:
      example:
        msg:
        - type: type
          value:
            amount:
            - amount: "50"
              denom: stake
            - amount: "50"
              denom: stake
            to_address: to_address
            from_address: from_address
        - type: type
          value:
            amount:
            - amount: "50"
              denom: stake
            - amount: "50"
              denom: stake
            to_address: to_address
            from_address: from_address
        fee:
          amount:
          - amount: "50"
            denom: stake
          - amount: "50"
            denom: stake
          gas: gas
        memo: memo
        signatures:
        - account_number: "0"
          sequence: "0"
          signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
          pub_key:
            type: tendermint/PubKeySecp256k1
            value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
        - account_number: "0"
          sequence: "0"
          signature: MEUCIQD02fsDPra8MtbRsyB1w7bqTM55Wu138zQbFcWx4+CFyAIge5WNPfKIuvzBZ69MyqHsqD8S1IwiEp+iUb6VSdtlpgY=
          pub_key:
            type: tendermint/PubKeySecp256k1
            value: Avz04VhtKJh8ACCVzlI8aTosGy0ikFXKIVHQ3jKMrosH
      properties:
        msg:
          items:
            $ref: '#/components/schemas/Msg'
          type: array
        fee:
          $ref: '#/components/schemas/StdTx_value_fee'
        memo:
          type: string
        signatures:
          items:
            $ref: '#/components/schemas/StdTx_value_signatures'
          type: array
    BlockID_parts:
      example:
        total: 0.0
        hash: EE5F3404034C524501629B56E0DDC38FAD651F04
      properties:
        total:
          example: 0.0
          type: number
        hash:
          example: EE5F3404034C524501629B56E0DDC38FAD651F04
          type: string
    BlockHeader_version:
      example:
        app: "0"
        block: "10"
      properties:
        block:
          example: "10"
          type: string
        app:
          example: "0"
          type: string
    Block_last_commit_precommits:
      example:
        round: "0"
        signature: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
        validator_address: validator_address
        validator_index: "0"
        type: 2.0
        block_id:
          parts:
            total: 0.0
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        height: "0"
        timestamp: 2017-12-30T05:53:09.287+01:00
      properties:
        validator_address:
          type: string
        validator_index:
          example: "0"
          type: string
        height:
          example: "0"
          type: string
        round:
          example: "0"
          type: string
        timestamp:
          example: 2017-12-30T05:53:09.287+01:00
          type: string
        type:
          example: 2.0
          type: number
        block_id:
          $ref: '#/components/schemas/BlockID'
        signature:
          example: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
          type: string
    Block_last_commit:
      example:
        block_id:
          parts:
            total: 0.0
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        precommits:
        - round: "0"
          signature: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
          validator_address: validator_address
          validator_index: "0"
          type: 2.0
          block_id:
            parts:
              total: 0.0
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          height: "0"
          timestamp: 2017-12-30T05:53:09.287+01:00
        - round: "0"
          signature: 7uTC74QlknqYWEwg7Vn6M8Om7FuZ0EO4bjvuj6rwH1mTUJrRuMMZvAAqT9VjNgP0RA/TDp6u/92AqrZfXJSpBQ==
          validator_address: validator_address
          validator_index: "0"
          type: 2.0
          block_id:
            parts:
              total: 0.0
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          height: "0"
          timestamp: 2017-12-30T05:53:09.287+01:00
      properties:
        block_id:
          $ref: '#/components/schemas/BlockID'
        precommits:
          items:
            $ref: '#/components/schemas/Block_last_commit_precommits'
          type: array
    BlockQuery_block_meta:
      example:
        header:
          validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          chain_id: cosmoshub-2
          consensus_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          total_txs: 35.0
          proposer_address: cosmos1depk54cuajgkzea6zpgkq36tnjwdzv4afc3d27
          next_validators_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          version:
            app: "0"
            block: "10"
          data_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          last_results_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          last_block_id:
            parts:
              total: 0.0
              hash: EE5F3404034C524501629B56E0DDC38FAD651F04
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          evidence_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          num_txs: 0.0
          app_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          time: 2017-12-30T05:53:09.287+01:00
          height: 1.0
          last_commit_hash: EE5F3404034C524501629B56E0DDC38FAD651F04
        block_id:
          parts:
            total: 0.0
            hash: EE5F3404034C524501629B56E0DDC38FAD651F04
          hash: EE5F3404034C524501629B56E0DDC38FAD651F04
      properties:
        header:
          $ref: '#/components/schemas/BlockHeader'
        block_id:
          $ref: '#/components/schemas/BlockID'
  securitySchemes:
    kms:
      scheme: basic
      type: http
